### PR TITLE
Update requirements.txt to work with stego.py

### PR DESCRIPTION
**Pull request by RaidTheWeb**

### CODE REVIEW

**Comment by sugarfi** [comment]
by the way, who is this? are you from repl.it or just some random programmer?

**Comment by RaidTheWeb** [comment]
I am from REPL.it and just a random programmer, liked your work and felt quite comfortable programming with it and decided you might want a stenography library.

**Comment by sugarfi** [comment]
ok, cool. I'm glad you like dour work.

**Comment by RaidTheWeb** [comment]
your welcome. BTW I have nothing to do and was wondering if you need anything made. ( Like a library or something ) :)

**Comment by sugarfi** [comment]
Sure! If you could implement a library for data storage (JSON, CSV, zip, etc.) that would be great. Also, how did you find out about this project?

**Comment by RaidTheWeb** [comment]
I have tried that and will make them, also I found out about this when I was creating an OS and needed inspiration for a IRC Client/Server program and found out about @RoylatGnail and their IRC.

**Comment by sugarfi** [comment]
OSDev, nice!

**Comment by RaidTheWeb** [comment]
here's a link to my testing enviroment: [https://repl.it/@RaidTheWeb/Quill-TE](url)

**Comment by sugarfi** [comment]
ok, cool.

**Comment by RaidTheWeb** [comment]
Do you possibly have a Dict datatype

**Comment by sugarfi** [comment]
yeah, it's called map

**Comment by sugarfi** [comment]
also, you should just join the discord to become a dev

**Comment by RaidTheWeb** [comment]
Ok. Great I can develop the JSON library now and how to join the discord

**Comment by AR-jpeg** [comment]
https://discord.gg/f3u3teD

**Comment by RaidTheWeb** [comment]
on the discord

**Pull request merged**
